export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const USER_LOAD = "USER_LOAD"
export const USER_FAIL = "USER_FAIL"
export const LOGOUT = "LOGOUT"

// add category constants
export const CATEGORY_CREATE = "CATEGORY_CREATE"
export const CATEGORY_ERROR = "CATEGORY_ERROR"
export const CATEGORIES_FETCH = "CATEGORIES_FETCH"

// add product constans
export const PRODUCT_CREATE = "PRODUCT_CREATE"
export const PRODUCT_READ = "PRODUCT_READ"
export const PRODUCT_DELETE = "PRODUCT_DELETE"
export const PRODUCT_UPDATE = "PRODUCT_UPDATE"
export const PRODUCT_ALL_READ = "PRODUCT_ALL_READ"
export const PRODUCT_ERROR = "PRODUCT_ERROR"
export const PRODUCTS_FETCH_BY_SOLD = "PRODUCTS_FETCH_BY_SOLD"
export const PRODUCTS_FETCH_BY_CREATEDAT = "PRODUCTS_FETCH_BY_CREATEDAT"
export const PRODUCTS_FETCH_BY_SEARCH = "PRODUCTS_FETCH_BY_SEARCH"
export const PRODUCTS_FETCH_BY_SEARCH_LOAD_MORE =
  "PRODUCTS_FETCH_BY_SEARCH_LOAD_MORE"
export const PRODUCTS_FETCH_BY_SEARCH_PATTERN =
  "PRODUCTS_FETCH_BY_SEARCH_PATTERN"

// create Orders
export const ORDER_CREATE = "ORDER_CREATE"
export const ORDER_FAIL = "ORDER_FAIL"
export const ODERS_FETCH_ALL = "ODERS_FETCH_ALL"
export const ORDER_STATUS_VALUES = "ORDER_STATUS_VALUES"
export const ORDER_STATUS_FAIL = "ORDER_STATUS_FAIL"
export const ORDER_STATUS_UPDATE = "ORDER_STATUS_UPDATE"
export const ORDER_STATUS_UPDATE_FAIL = "ORDER_STATUS_UPDATE_FAIL"

// payment token
export const PAYMENT_TOKEN = "PAYMENT_TOKEN"
export const PAYMENT_TOKEN_FAIL = "PAYMENT_TOKEN_FAIL"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAIL = "PAYMENT_FAIL"

// cart actions
export const CART_ADDITEM = "CART_ADDITEM"
export const CART_UPDATE = "CART_UPDATE"
export const CART_REMOVEITEM = "CART_REMOVEITEM"
export const CART_DELETE = "CART_DELETE"

// user actions
export const USER_READ = "USER_READ"
export const USER_UPDATE = "USER_UPDATE"
export const USER_PURCHASE_HISTORY = "USER_PURCHASE_HISTORY"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"
